---
- name: Install dependencies
  apt:
    cache_valid_time: 3600
    name:
      - postfix

- name: Postfix user is created
  user:
    name: postfix
    system: yes
    create_home: no
    shell: /sbin/nologin

- name: Place configuration files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: 0600
  with_items:
    - src: 'templates/main.cf.j2'
      dest: '/etc/postfix/main.cf'
    - src: 'templates/master.cf.j2'
      dest: '/etc/postfix/master.cf'
  notify: restart postfix

- name: Create maildir when user login
  file:
    path: '/etc/skel/{{ postfix_home_maildir }}{{ item }}'
    state: directory
    mode: 0700
    owner: root
    group: root
  with_items:
    - ''
    - 'new'
    - 'cur'
    - 'tmp'

- name: Aliases are up-tp-date
  templates:
    src: "templates/aliases.j2"
    dest: "/etc/aliases"
  notify: Renew aliase db

- name: Postfix started
  service:
    name: postfix
    state: started
